### ISSUE TITLE
Activity formatting issue

### ISSUE THREAD

**Issue by DeviousLab** [Readme-Workflows/recent-activity#132] opened 2021-11-18 16:37 UTC
I'm having this issue where my activity does not format as it should, and takes up a large amount of space. Is there anything that might be missing from my readme or the workflow that could be causing this?

![Screenshot_20211118_195717](https://user-images.githubusercontent.com/53790060/142456792-e4440e4c-1715-4f26-9ae7-22a1bcf17439.png)

**Comment by Andre601** [comment] 2021-11-18 16:39
Can you please share your current workflow and the config file of the recent-activity action?

**Comment by PuneetGopinath** [comment] 2021-11-19 02:39
Hey @DeviousLab 

I have looked in your profile repo, and I have found there's no config file at all

There's where the problem comes I guess, it is required to have a config file

You can copy our [example config file]() and put it in your profile repo, inside the `.github` folder (not inside `.github/workflows`)

Please let me know if the problem is solved after adding the config file so we can close this issue!

**Comment by abhijoshi2k** [comment] 2021-11-20 08:02
@DeviousLab Please check [PR on your Repo](https://github.com/DeviousLab/DeviousLab/pull/2) which will resolve this issue.
Please reopen this issue if it's not resolved after merging the above mentioned PR.

**Closed by abhijoshi2k** 2021-11-20 08:02 UTC

**Comment by DeviousLab** [comment] 2021-11-20 18:52
Thank you all for your help, the issue is resolved now!
